package outdoorapp.utils;

/**
 * Interfaccia che contiene tutte le chiavi-valore per far visualizzare le view
 * 
 * @author Andrea Zito
 * @author Francesco Ventura
 *
 */

public interface Views {
	public static final String VIEW_LOGIN = "VIEW_LOGIN";
	public static final String VIEW_MANAGER_DI_SISTEMA_CONFIG = "VIEW_MANAGER_DI_SISTEMA_CONFIG";
	public static final String VIEW_DASHBOARD_MANAGER_DI_SISTEMA = "VIEW_DASHBOARD_MANAGER_DI_SISTEMA";
	public static final String VIEW_DASHBOARD_MANAGER_DI_ESCURSIONE = "VIEW_DASHBOARD_MANAGER_DI_ESCURSIONE";
	public static final String VIEW_DASHBOARD_PARTECIPANTE = "VIEW_DASHBOARD_PARTECIPANTE";
	public static final String VIEW_PASSWORD_DIMENTICATA = "VIEW_PASSWORD_DIMENTICATA";
	public static final String VIEW_REGISTRAZIONE_PARTECIPANTE = "VIEW_REGISTRAZIONE_PARTECIPANTE";
	public static final String VIEW_GESTIONE_MANAGER_ESCURSIONE = "VIEW_GESTIONE_MANAGER_ESCURSIONE";
	public static final String VIEW_VISUALIZZA_ESCURSIONI_SISTEMA = "VIEW_VISUALIZZA_ESCURSIONI_SISTEMA";
	public static final String VIEW_REGISTRAZIONE_MANAGER_ESCURSIONE = "VIEW_REGISTRAZIONE_MANAGER_ESCURSIONE";
	public static final String VIEW_GESTIONE_ESCURSIONI = "VIEW_GESTIONE_ESCURSIONI";
	public static final String VIEW_INSERISCI_ESCURSIONE = "VIEW_INSERISCI_ESCURSIONE";
	public static final String VIEW_LE_MIE_ESCURSIONI = "VIEW_LE_MIE_ESCURSIONI";
	public static final String VIEW_VISUALIZZA_ESCURSIONI_APERTE = "VIEW_VISUALIZZA_ESCURSIONI_APERTE";
	public static final String VIEW_IL_MIO_PROFILO = "VIEW_IL_MIO_PROFILO";
	public static final String VIEW_DETTAGLI_MANAGER_DI_ESCURSIONE = "VIEW_DETTAGLI_MANAGER_DI_ESCURSIONE";
	public static final String VIEW_MODIFICA_MANAGER_DI_ESCURSIONE = "VIEW_MODIFICA_MANAGER_DI_ESCURSIONE";
	public static final String VIEW_DETTAGLI_ESCURSIONI = "VIEW_DETTAGLI_ESCURSIONI";
	public static final String VIEW_DETTAGLI_PARTECIPANTE = "VIEW_DETTAGLI_PARTECIPANTE";
	public static final String VIEW_DETTAGLI_ESCURSIONI_FROM_MDE = "VIEW_DETTAGLI_ESCURSIONI_FROM_MDE";
	public static final String VIEW_MODIFICA_ESCURSIONE = "VIEW_MODIFICA_ESCURSIONE";
	public static final String VIEW_AGGIORNA_SRC_PARTECIPANTE = "VIEW_AGGIORNA_SRC_PARTECIPANTE";
	public static final String VIEW_MODIFICA_DATI_PARTECIPANTE = "VIEW_MODIFICA_DATI_PARTECIPANTE";
	public static final String VIEW_ISCRITTI_ESCURSIONE = "VIEW_ISCRITTI_ESCURSIONE";
	public static final String VIEW_ISCRIZIONE_ESCURSIONE = "VIEW_ISCRIZIONE_ESCURSIONE";
}
